# Generated by Django 4.0.3 on 2023-07-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.URLField(null=True, unique=True),
        ),
    ]
