# Generated by Django 4.0.3 on 2023-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_technician_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
    ]
