# Generated by Django 4.0.3 on 2023-07-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_technician_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('first_name',)},
        ),
    ]
