# Generated by Django 4.0.3 on 2023-07-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_technician_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='import_hred',
            new_name='import_href',
        ),
    ]
