# Generated by Django 4.0.3 on 2023-07-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_rename_import_hred_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='status_id',
        ),
    ]
